### ISSUE TITLE
After registration they should be auto-logged in to the app

### ISSUE THREAD

**Issue by leggetter** [tru-ID/passwordless-auth-phonecheck#4]
The app presently shows them a login screen which would mean there's duplicate effort. The phone number has been successfully verified so they should be auto-logged in and taken to a success/welcome screen. This will be a good starting point for other tutorials.

Having the completed login functionality in the completed application is also find IMHO. That way future tutorials that use this as a starting point can utilise registration or login. For step-up auth I think it's likely from the login.

**Comment by glamboyosa** [comment]
shows a `home` screen now

**Comment by glamboyosa** [comment]
as will be shown in the companion app

**Comment by glamboyosa** [comment]
step-up will use https://reactnavigation.org/
